plugins {
    id 'java'
    id("net.bytebuddy.byte-buddy-gradle-plugin") version "1.18.7-jdk5"
}

group = 'nsu.sd'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    testCompileOnly 'org.projectlombok:lombok:1.18.42'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.42'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.0'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.20.0'
    implementation 'net.bytebuddy:byte-buddy:1.14.12'
}

test {
    useJUnitPlatform()
}